---
title: Student Loan Debt
author: Matthew Henderson
date: '2019-11-26'
slug: student-loan-debt
categories: []
tags: []
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  collapse = TRUE
)

ggplot2::theme_set(hrbrthemes::theme_ipsum_rc())
```

```{r}
library(tidyverse)
library(viridis)

data_root("tidy_student_loans.rds") %>%
  read_rds() %>%
  ggplot(aes(
    x = quarter_year_date,
    y = total,
    colour = method)) +
  geom_line() +
  scale_fill_viridis(discrete = T) +
  scale_y_continuous(breaks = seq(0, 8, 1)) +
  labs(
       title = "Student Loan Payments",
    subtitle = "By Quarter : 2015-2018",
           x = "Year",
           y = "USD (billion)",
     caption = "Based on code by @LarissaKostiw. Data: Dep. of Education"
  ) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
          plot.title = element_text(hjust=0.5, face="bold"),
       plot.subtitle = element_text(hjust=0.5, face="bold"),
        plot.caption = element_text(hjust=1),
         legend.text = element_text(size=9),
        legend.title = element_text(face="bold"),
           axis.text = element_text(face="italic"),
          axis.title = element_text(face="bold", size=12)
  )
```
