---
title: 'Tidy Tuesday: Replicating Plots in R'
author: Matthew Henderson
date: '2021-11-10'
description: "Week 50 of 2019."
slug: [tidy-tuesday-replicating-plots-in-r]
categories:
  - dataviz
tags:
  - tidy-tuesday
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
       cache = FALSE,
        echo = TRUE,
     message = FALSE,
     warning = FALSE,
     comment = "#>",
    collapse = TRUE,
   fig.width = 8,
  fig.height = 8
)
```

Tidy Tuesday
in week fifty of 2019
was all about
[this blog post](https://simplystatistics.org/2019/08/28/you-can-replicate-almost-any-plot-with-ggplot2/)
by Rafael Irizarry
on replicating plots in R.

I chose to focus on a heatmap showing
infectious diseases in the United States
before and after
the introduction of vaccines.

My plot is heavily based
on Rafael's code with
just a few extra annotations
and a change of scale
to match the
[original version](http://graphics.wsj.com/infectious-diseases-and-vaccines/?mc_cid=711ddeb86e)
published in the Wall Street Journal.

This was my first attempt at adding annotations outside
the main plotting area.
I learned how to
create the annotations
I wanted for this plot
from the Tidy Tuesday work of Georgios Karamanis.
Especially his
[week 36 entry for 2021.](https://github.com/gkaramanis/tidytuesday/tree/master/2021/2021-week36)

My code is here:
https://github.com/MHenderson/replicating-plots-in-r

![Plot shows a heat map of measles cases per one hundred thousand people measured from 1928 to 2003 across all fifty US states and the District of Columbia. Showing that after 1963 when measles vaccine was introduced there was a dramatic drop in the number of measles cases throughout the United States.](diseases.png)
