baseurl: "/"
languageCode: "en-us"
title: "Dr. Matthew Henderson"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
      pre: <i class='fa fa-home'></i>
    - name: Categories
      url: "categories/"
      weight: 2
      pre: <i class='fa fa-list'></i>
    - name: Tags
      url: "tags/"
      weight: 3
      pre: <i class='fa fa-tags'></i>
    - name: Subscribe
      url: "index.xml"
      pre: <i class='fa fa-rss'></i>

params:
  description: "My personal website."
  footer: "&copy; [Matthew Henderson]() 2021 | [Github](https://github.com/MHenderson) | [Twitter](https://twitter.com/masatthew)"
  twitterAuthor: "@masatthew"
  twitterSite: "https:://mjh.netlify.app"

markup:
  goldmark:
    renderer:
      unsafe: true
