baseurl: "https://mjh.netlify.app/"
languageCode: "en-us"
title: "mjhdata"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
      pre: <i class='fa fa-home'></i>
    - name: Posts
      url: "post/"
      weight: 2
      pre: <i class='fa fa-list'></i>
    - name: Categories
      url: "categories/"
      weight: 4
      pre: <i class='fa fa-sitemap'></i>
    - name: Tags
      url: "tags/"
      weight: 5
      pre: <i class='fa fa-tags'></i>
    - name: Subscribe
      url: "index.xml"
      pre: <i class='fa fa-rss'></i>

params:
  description: "My personal website."
  footer: "&copy; [Matthew Henderson]() 2021"
  twitterAuthor: "@masatthew"
  twitterSite: "https:://mjh.netlify.app"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "colorful"
    tabWidth: 4
