baseurl: "/"
languageCode: "en-us"
title: "Dr. Matthew Henderson"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "My personal website."
  footer: "&copy; [Matthew Henderson]() 2021 | [Github](https://github.com/MHenderson) | [Twitter](https://twitter.com/masatthew)"

markup:
  goldmark:
    renderer:
      unsafe: true
