---
title: Home
---

```{r, echo=FALSE}
library(htmltools)
library(magrittr)
library(shiny)

div(
  id = "contact",
  h1("Dr. Matthew Henderson"),
  tags$ul(
    tags$li(
      a(
        icon("envelope"),
        span("Email"),
        href = "mailto:matthew.james.henderson@gmail.com"
      )
    ),
    tags$li(
      a(
        icon("linkedin"),
        span("LinkedIn"),
        href = "https://www.linkedin.com/in/matthew-henderson-2a5b26193"
      )
    ),
    tags$li(
      a(
        icon("github"),
        span("Github"),
        href = "https://github.com/MHenderson"
      )
    ),
    tags$li(
      a(
        icon("gitlab"),
        span("Gitlab"),
        href = "https://gitlab.com/MHenderson1"
      )
    ),
    tags$li(
      a(
        icon("bitbucket"),
        span("Bitbucket"),
        href = "https://bitbucket.com/matthew"
      )
    )
  )
)
```

```{r, echo=FALSE}
posts_col <- div(
  h1("Posts"),
  id = "latest-posts",
  class = "column",
  tags$ul(
    tags$li(
      "2021/05/11",
      a(
        "Tidy Tuesday: Internet Access",
        href = "/post/2021/05/11/internet-access/"
      )
    ),
    tags$li(
      "2021/05/04",
      a(
        "Tidy Tuesday: Water Sources",
        href = "/post/2021/05/04/water-sources/"
      )
    ),
    tags$li(
      "2018/01/16",
      a(
        "Functional Geometry in R",
        href = "/post/2018/01/16/functional-geometry-in-r/"
      )
    ),
    tags$li(
      a(
        "more ...",
        href = "/post"
      )
    )
  )
)
```

```{r, echo=FALSE}
projects_col <- div(
  h1("Research"),
  id = "highlighted-projects",
  class = "column",
  tags$ul(
    tags$li(
      a(
        "Room Squares",
        href = "/topics/room-squares"
      )
    ),
    tags$li(
      a(
        "Energy Use",
        href = "/topics/energy-use"
      )
    ),
    tags$li(
      a(
        "more ...",
        href = "/projects"
      )
    )
  )
)
```

```{r, echo=FALSE}
div(
  class = "row",
  posts_col,
  projects_col
)
```

