---
title: Writing 
author: Matthew Henderson
date: '2019-12-10'
slug:
categories: []
tags: []
publishdate: '2019-12-10'
lastmod: '2019-12-10'
editor_options: 
  chunk_output_type: console
description: Week 50
images:
- post/2019-12-10-replicating-plots-in-r/index_files/figure-html/murders-cover-1.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
        echo = FALSE,
     message = FALSE,
     warning = FALSE,
     comment = "#>",
    collapse = TRUE,
   fig.width = 8,
  fig.height = 8
)

ggplot2::theme_set(hrbrthemes::theme_ipsum_rc())
```

## Blog

My blog is here: https://www.dorsetdata.com/

## Tidy Tuesday

My work for Tidy Tuesday can be found here: https://mjh-tidy-tuesday.netlify.com/

## Coding with Graphs

A blog I wrote in 2014 about using data pipelines
involving Python and Maxima to work with graphs cab
be found here: https://coding-with-graphs.netlify.com/

## Room Squares

A book about Room Squares: https://room-squares.netlify.com/

## PhD Thesis

My PhD thesis in bookdown format: https://mjh-phd.netlify.com/

## Selected Publications

```{r, results='asis'}
library(tidyverse)
library(glue)
library(here)
library(readxl)

here("data-raw", "works.xlsx") %>%
  read_xlsx("publications") %>%
  glue_data(
    "{Year}",
    "\n\n",
    ":    {Title} by {Authors} in {Publication}",
    "\n\n"
  )
```

## Notes

```{r, results='asis'}
here("data-raw", "works.xlsx") %>%
  read_xlsx("notes") %>%
  glue_data(
    "* [{title}]({url_short}) - {description}"
  )
```

## Notebooks

```{r, results='asis'}
here("data-raw", "works.xlsx") %>%
  read_xlsx("notebooks") %>%
  glue_data(
    "* [{title}]({url}) - {description}"
  )
```

## Slides

* http://conference.scipy.org/scipy2010/slides/matthew_henderson_sudoku.pdf

## Lecture notes?
