---
title: "Room Square objects in R using R6"
author: "Matthew Henderson"
date: '2023-05-12'
description: Implementing Room squares in R using R6.
slug: more-maximal-room-squares
categories:
 - combinatorics
tags:
 - room-squares
editor_options:
  chunk_output_type: console
draft: yes
featured: no
references:
- id: meszkaMaximalPartialRoom2021
  abstract: A partial Room square is maximal if no further pair of elements can be
    placed into any unoccupied cell without violating the conditions that define a
    partial Room square. This article is concerned with determining the spectrum of
    volumes of maximal partial Room squares of order n where the volume is the number
    of occupied cells and the order n is even.
  accessed:
  - year: 2021
    month: 7
    day: 21
  author:
  - family: Meszka
    given: Mariusz
  - family: Rosa
    given: Alexander
  container-title: Journal of Combinatorial Designs
  DOI: 10.1002/jcd.21777
  ISSN: 1520-6610
  issue: '7'
  issued:
  - year: 2021
  language: en
  note: '_eprint: https://onlinelibrary.wiley.com/doi/pdf/10.1002/jcd.21777'
  page: 482-501
  source: Wiley Online Library
  title: Maximal partial Room squares
  type: article-journal
  URL: https://onlinelibrary.wiley.com/doi/abs/10.1002/jcd.21777
  volume: '29'
- id: hendersonMHendersonMaximalroomsquares2023
  abstract: >-
    <strong>Full Changelog</strong>:
    https://github.com/MHenderson/maximal-room-squares/commits/0.1.0
  accessed:
    - year: 2023
      month: 5
      day: 4
  author:
    - family: Henderson
      given: Matthew
  citation-key: hendersonMHendersonMaximalroomsquares2023
  DOI: 10.5281/ZENODO.7895562
  issued:
    - year: 2023
      month: 5
      day: 4
  license: Open Access
  publisher: Zenodo
  source: DOI.org (Datacite)
  title: 'MHenderson/maximal-room-squares: 0.1.0'
  title-short: MHenderson/maximal-room-squares
  type: software
  URL: https://zenodo.org/record/7895562
  version: 0.1.0
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
        echo = TRUE,
     message = FALSE,
     warning = FALSE,
     comment = "#>",
    collapse = TRUE
)
```


In Meszka and Rosa (2021) the authors investigate the spectra of maximal partial Room squares.

In this post we reproduce the table from that paper.

## Motivation

Why bother? There is almost no point at all.

Something left open from the paper as a question (not really, but sort of) is whether the maximum proportion achieved is bounded. In other words if we run one of the two determinsitc greedy processes then are we only ever going to see about 88% filled cells. We can't really answer that with small scale computer experiments but at least we can rule out a small counter-example.

The real motivation for myself is that I am interested in seeing if other methods might help to fill in some of those missing cases. So it seems like a good first step is to merely reproduce what has already been done. So that will be the point of this post. Mostly as a personal reference about the code I've written and how to reproduce these experiments.

Another motivation I have is that of being experimental. Maybe I will discover something just by playing around with these things. In fact I think I did make a very small discovery in noticing that there is no reason to limit our experiments to the odd orders as we do for Room squares. But I don't know if I can make a persuavive case or not.

In particular here we make use of R, **renv** and **targets** in the goal of having reproducible code. It would be nice to be able to have code that shows how to run everything inside of a Docker container so that we can be sure that it is preserved for the ages.

Another one is that the implementation from the first post was very slow so I had another go at a different implementation that might be faster.

Another reason is to have a source for the table in order to possibly extend it. We could just copy the table from the paper but that would potentially propagate any mistakes that might happen to appear in that table against the purpose of reproducibility.


## References
