---
title: Spotify Songs
author: Matthew Henderson
date: '2020-01-21'
slug: spotify-songs
categories: []
tags: []
publishdate: '2019-01-21'
lastmod: '2019-01-21'
editor_options: 
  chunk_output_type: console
description: Week 4
images:
- post/2020-01-21-spotify-songs/index_files/figure-html/speechiness-1.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  collapse = TRUE
)

ggplot2::theme_set(hrbrthemes::theme_ipsum_rc())
spotify_songs <- readr::read_rds(here::here("content", "post", "2020-01-21-spotify-songs", "spotify_songs.rds"))
```

```{r duration}
library(tidyverse)

spotify_songs %>%
  mutate(
    duration_s = duration_ms / 1000,
    duration_m = duration_s / 60
  ) %>%
  ggplot(aes(duration_m, colour = playlist_genre)) +
    geom_freqpoly() +
    labs(
            x = "duration (mins)",
            y = "",
        title = "Song length",
      caption = "data from Kaylin Pavlik"
    )
```

```{r danceability}
spotify_songs %>%
  pivot_longer(c("danceability", "energy")) %>%
  ggplot(aes(value, colour = playlist_genre)) +
    geom_freqpoly() +
    facet_wrap(~name) +
    labs(
            x = "",
            y = "",
        title = "Energy and danceability",
      caption = "data from Kaylin Pavlik"
    )
```

```{r speechiness}
spotify_songs %>%
  pivot_longer(c("speechiness","liveness")) %>%
  ggplot(aes(log(value), colour = playlist_genre)) +
    geom_freqpoly(binwidth = .1) +
    facet_wrap(~name, scales = "free") +
    labs(
            x = "",
            y = "",
        title = "",
      caption = "data from Kaylin Pavlik"
    )
```

```{r acousticness}
spotify_songs %>%
  pivot_longer(c("acousticness","instrumentalness")) %>%
  ggplot(aes(log(value), colour = playlist_genre)) +
    geom_freqpoly(binwidth = .5) +
    facet_wrap(~name, scales = "free") +
    labs(
            x = "",
            y = "",
        title = "",
      caption = "data from Kaylin Pavlik"
    )
```

```{r tempo}
spotify_songs %>%
  pivot_longer(c("tempo")) %>%
  ggplot(aes(value, colour = playlist_genre)) +
    geom_freqpoly(binwidth = 1) +
    facet_wrap(~name, scales = "free") +
    labs(
            x = "",
            y = "",
        title = "",
      caption = "data from Kaylin Pavlik"
    )
```
