---
title: Software 
author: Matthew Henderson
date: '2019-12-10'
slug:
categories: []
tags: []
publishdate: '2019-12-10'
lastmod: '2019-12-10'
editor_options: 
  chunk_output_type: console
description: Week 50
bibliography: [../../static/bib/yours_truly.bib]
link-citations: true
images:
- post/2019-12-10-replicating-plots-in-r/index_files/figure-html/murders-cover-1.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
        echo = FALSE,
     message = FALSE,
     warning = FALSE,
     comment = "#>",
    collapse = TRUE,
   fig.width = 8,
  fig.height = 8
)

ggplot2::theme_set(hrbrthemes::theme_ipsum_rc())
```

```{r packages, include=FALSE}
library(tidyverse)
library(glue)
library(here)
library(readxl)

packages <- here("works", "works.xlsx") %>%
  read_xlsx("packages") %>%
  mutate(
    repo = case_when(
      !is.na(github) ~ github,
      !is.na(gitlab) ~ gitlab,
      !is.na(bitbucket) ~ bitbucket,
      TRUE ~ github
    )
  )

applications <-  here("works", "works.xlsx") %>%
  read_xlsx("applications") %>%
  filter(title!="htmlwidgets") %>%
  mutate(
    bitbucket = as.character(bitbucket),
    repo = case_when(
      !is.na(github) ~ github,
      !is.na(gitlab) ~ gitlab,
      !is.na(bitbucket) ~ bitbucket,
      TRUE ~ github
    )
  )
```

## Applications

```{r applications, results='asis'}
applications %>%
  filter(!is.na(homepage)) %>%
  glue_data(
    "\n\n",
    "## {title}",
    "\n\n",
    "{description}",
    "\n\n",
    paste(shiny::icon("home"), "{homepage}"),
    "\n\n",
    paste(shiny::icon("github"), "{repo}"),
    "\n\n"
  )
```

## Packages

```{r with_homepage, results='asis'}
packages %>%
  filter(!is.na(homepage)) %>%
  glue_data(
    "\n\n",
    "## {title}",
    "\n\n",
    "{description}",
    "\n\n",
    paste(shiny::icon("home"), "{homepage}"),
    "\n\n",
    paste(shiny::icon("github"), "{repo}"),
    "\n\n"
  )
```

```{r no_homepage, results='asis'}
packages %>%
  filter(is.na(homepage)) %>%
  glue_data(
    "\n\n",
    "## {title}",
    "\n\n",
    "{description}",
    "\n\n",
    paste(shiny::icon("github"), "{repo}"),
    "\n\n"
  )
```

## References
