---
title: "(WIP) Generating Nonsense with MarkovifyR"
author: Matthew Henderson
date: '2018-01-04'
slug: markovifyr
categories:
  - nlp
tags:
  - r
draft: TRUE
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  fig.height = 4,
  fig.width = 8
)
```

# MarkovifyR

This post is all about the R package [**markovifyR**](https://github.com/abresler/markovifyR) by
Alex Bresler.

Let's use Whitman's *Leaves of Grass* as a starting point.

```{r}
library(gutenbergr)

leaves_of_grass <- gutenberg_download(1322, mirror = "http://www.mirrorservice.org/sites/ftp.ibiblio.org/pub/docs/books/gutenberg/")
```

```{r}
library(tidyverse)
library(tidytext)

(tidyleaves <- tibble(txt = leaves_of_grass$text) %>%
  unnest_tokens(sentence, txt, token = "sentences"))
```

```{r}
library(markovifyR)

markov_model <-
  generate_markovify_model(
    input_text = tidyleaves %>% pull(sentence),
    markov_state_size = 2L,
    max_overlap_total = 5,
    max_overlap_ratio = .4
  )
```

```{r}
results <- markovify_text(
  markov_model = markov_model,
  maximum_sentence_length = NULL,
  output_column_name = 'waltWhitman',
  count = 5,
  tries = 300,
  only_distinct = TRUE,
  return_message = FALSE
)
```

```{r}
library(glue)
library(htmltools)

results %>%
  glue_data("{waltWhitman}") %>%
  glue_collapse(sep = " ") %>%
  tags$p()
```
