---
title: NFL Attendance 
author: Matthew Henderson
date: '2020-02-04'
slug: nfl-attendance
categories: []
tags: []
publishdate: '2019-02-04'
lastmod: '2019-02-04'
editor_options: 
  chunk_output_type: console
description: Tidy Tuesday Week 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  collapse = TRUE
)

ggplot2::theme_set(hrbrthemes::theme_ipsum_pub())

options("scipen"=100, "digits"=4)
```

```{r duration, fig.width=15, fig.height=10}
library(tidyverse)

attendance <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv')

standings <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv')

games <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/games.csv')

attendance %>%
  left_join(standings, by = c("year", "team_name", "team")) %>%
  mutate(team = paste(team, team_name)) %>%
  filter(year==2003) %>%
  ggplot(aes(week, weekly_attendance)) +
  geom_step() +
  geom_smooth() +
  facet_wrap(~team)
```

